### ISSUE TITLE
No way to get single ip in "asset find" output

### ISSUE THREAD

**Issue by ssgelm** [tumblr/collins_shell#2]
It's possible I am missing something, but as far as I can tell there is no ability to get a single ip from a specific pool with either `--tags` or `--exec` when doing an `collins-shell asset find`.  We generally have IPs from two separate pools assigned to each asset and it seems to me the only option is to use the `addresses` tag and parse that outside of collins-shell.  Is that correct?

**Comment by defect** [comment]
Closed in #3. Thank you!
